language: go
go:
- tip
script:
- go test -v -timeout 1m -cpu 1,2,4 -count 4
- go vet -v .
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#/dev/null
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
    skip_join: false
